name: issues-to-project

# Controls when the workflow will run
on:
  issues:
    types: [opened]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  assign:
    name: Assign issues to project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issues to project
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: Stedi Public Roadmap
          COLUMN: Researching
  
